### ISSUE TITLE
Refactor weighted tree loading to be "public"

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-accounting#102]
#97 adds the ability to create a populated weighted tree from an accounting DB for testing purposes.  That functionality will be required moving forward to handle #63.  To make this easier, we should pull the `load_accounting_db.*` out of the `test` directory and up a level into `weighted_tree`.

**Comment by cmoussa1** [comment]
Does this also include adding `load_accounting_db.*` to `libweighted_tree_la_SOURCES` in the Makefile in `weighted_tree/`?

```make
libweighted_tree_la_SOURCES = \
    ../account/account.cpp \
    weighted_tree.cpp \
    weighted_walk.cpp \
    ../account/account.hpp \
    weighted_tree.hpp \
    weighted_walk.hpp
```
