### ISSUE TITLE
test infrastructure for multifactor priority plugin with multiple users

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#125]
I've been thinking about how we can easily expand testing of the multifactor priority plugin proposed in #122 to multiple users. Eventually, we will want to test the "end to end" system in something like the fluxorama docker container to simulate a real system instance as closely as possible, however, it occurs to me there are some simple tools we can use now to get some good test coverage even when doing a local `make check` in the build directory of `flux-accounting`.

In flux-core, we already make use of some environment variables and library code to simulate submission of jobs by a guest user. This includes the `FLUX_HANDLE_USERID` environment variable, which allows the instance owner to simulate a local connection from an arbitrary user, and the flux-security `flux_sign_wrap_as(3)` function which allows signing a payload as an arbitrary userid.

Putting these two together, we are able to submit jobs as arbitrary userids in testing using the "none" signing mechanism.

I've put together the following Python script, which allows jobs to be submitted as an arbitrary userid. In this prototype, actual job execution is disabled, since it would fail, but more importantly jobs could be easily enqueued with various test userids and behavior of the mf_priority.so plugin tested.

If this is useful, perhaps we can expand upon this script to read in an entire set of jobs, along with their submission order, job sizes, other flux-mini arguments (e.g. requested bank) from a file to create an input workload for tests. We then just have to figure out how we'll gauge that the priority plugin behaved in the expected manner.

One idea to start would be to do testing without a scheduler or with the queue stopped (`flux queue stop`) so no jobs are actually run. Then submit a given set of jobs and ensure the queue is in the expected order and/or jobs have correct relative priorities.

I think this will give us good testing mileage to start, and perhaps we won't (quite yet) have to figure out how to drive automated testing inside the fluxorama system instance container.

Usage of the script below:
```console
$ ./submit-as.py 
Usage: submit-as USERID [MINI OPTS...] COMMAND
$ ./submit-as.py 42 hostname
ƒTDFNYVd
$ ./submit-as.py 128 -n2  hostname
ƒZbM9FnP
$ ./submit-as.py 42 -N2 -n2  hostname
ƒfDasDVR
$ flux jobs -A
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒfDasDVR 42       hostname   CD      2      2   0.007s asp,asp
    ƒZbM9FnP 128      hostname   CD      2      1   0.004s asp
    ƒTDFNYVd 42       hostname   CD      1      1   0.005s asp

```

```python
#!/usr/bin/env python3

import os
import sys
import argparse
from subprocess import Popen, PIPE

import flux
from flux.security import SecurityContext


def run_process(cmd, input=None):
    """Run command defined in `cmd` as a subprocess and return stdout

    If `input` is given, send to subprocess stdin.

    Copy any stderr to terminal and exit with error on subprocess failure.
    """

    with Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE) as proc:
        out, err = proc.communicate(input)
        if err:
            sys.stderr.write(err.decode("utf-8"))
        if proc.returncode != 0:
            sys.exit(1)
        return out.decode("utf-8").rstrip()


def main():

    if len(sys.argv) < 3:
        sys.exit(f"Usage: submit-as USERID [MINI OPTS...] COMMAND")

    userid = int(sys.argv[1])
    os.environ["FLUX_HANDLE_USERID"] = str(userid)

    minicmd = [
        "flux",
        "mini",
        "run",
        "--dry-run",
        "--setattr=system.exec.test.duration=0.1",
        *sys.argv[2:],
    ]
    jobspec = run_process(minicmd)

    signedJ = SecurityContext().sign_wrap_as(userid, jobspec, mech_type="none")

    submitcmd = ["flux", "job", "submit", "--flags=signed"]
    jobid = run_process(submitcmd, input=signedJ)
    print(jobid)


if __name__ == "__main__":
    main()
```

**Comment by cmoussa1** [comment]
Thanks again for taking the time to put this together @grondo - this is going to be one of the things I think I'll focus on in the next month for flux-accounting. 

> If this is useful, perhaps we can expand upon this script to read in an entire set of jobs, along with their submission order, job sizes, other flux-mini arguments (e.g. requested bank) from a file to create an input workload for tests. We then just have to figure out how we'll gauge that the priority plugin behaved in the expected manner.

One strategy that comes to mind to gauge that the priority plugin is behaving expectedly is to leverage some of the fairshare unit tests we wrote in `src/fairness/`. More specifically, a subset of tests run in that directory is making sure the correct order of users is output after re-ordering users according to their fairshare. Maybe I could create and send a fake payload using the data from these tests and submit the same type of job as each of these users, comparing the ordering from `flux jobs -A` to the expected order from the unit tests.

**Comment by cmoussa1** [comment]
#129 added tests for the plugin with multiple users, so I think I can close this issue. If the performance of the `submit_as.py` script starts to become an issue or anything with many many users or job submissions, I can open a more specific issue regarding improving the script itself.
