### ISSUE TITLE
mergify: replace strict mode merge with queue

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#159]
Mergify is deprecating the `strict` merge mode in the near future.

https://blog.mergify.io/strict-mode-deprecation/

The mergify config in this repo should be updated to use the queue based method. Possibly you can just copy what was done for flux-core in flux-framework/flux-core#3907.

**Comment by cmoussa1** [comment]
I forgot to tag this issue when I created PR #160 to address this, so I'll close it now.
