### ISSUE TITLE
database: change default DB path location

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#168]
While reviewing flux-framework/flux-docs#109, @garlick made a suggestion to change the default database path location to `@X_LOCALSTATEDIR@/lib/flux/FluxAccounting.db`. This should be a relatively straightforward fix, as I think this just involves changing the value of `db_dir` and `db_path` in `/src/bindings/python/fluxacct/accounting/__init__.py.in`:

```make
db_dir = "@X_LOCALSTATEDIR@/lib/flux/"
db_path = "@X_LOCALSTATEDIR@/lib/flux/FluxAccounting.db"
``` 

When building the project from source, I can use the following:

```shell
./autogen && ./configure --localstatedir=/var/ && make -j && make check
```

to create a default DB location for `/var/lib/flux/`. I'm sorry in advance that I do not know autotools very well; does this approach seem reasonable or make sense @garlick?

Regardless, as long as the person or people administering the DB has permissions to this directory, then they should be able to interact with this DB, i.e adding banks and users, editing their information, and more.

**Comment by garlick** [comment]
Yes that sounds right.  The `@X_LOCALSTATEDIR@` macro comes from `x_ac_expand_install_dirs.m4` which you have, and `--localstatedir=/var` matches the instructions at the top of the admin guide, intended for building all the packages.

**Comment by cmoussa1** [comment]
Great! I'll post a PR shortly with this change. Would you mind if I tagged you as a reviewer?

**Comment by garlick** [comment]
That would be fine!
