### ISSUE TITLE
update-usage: add default path support to job-archive DB

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#174]
During the review process in flux-framework/flux-docs#109, there was mention of adding default path support for accessing the job-archive DB. 

Currently, the `update-usage` subcommand requires a positional database path argument, but it would be nice to support a default path to the command that accesses this DB, especially if the job-archive DB resides in the same location as the flux-accounting DB.

**Comment by garlick** [comment]
Maybe go with  `@X_LOCALSTATEDIR@/lib/flux/job-archive.sqlite`

We don't currently have a default in job-archive but maybe that should change.

**Comment by garlick** [comment]
On second thought, why don't we hold off on this.  This is going to be a coordination issue between `job-archive` and this project and we should probably give it a bit more design effort.

**Comment by cmoussa1** [comment]
OK, that sounds good. I like that plan!

**Comment by cmoussa1** [comment]
I don't think this issue is entirely necessary anymore since flux-accounting has since implemented its own job-archive, so I'll close this now.
