### ISSUE TITLE
[discussion] FluxAccounting.db: database file protection

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#18]
A question that came up during today's call was how to protect the SQLite database file in flux-accounting. 

One option that comes to mind is to protect the file with just Unix file permissions, only allowing read/write access to the admins and/or those who manage user accounts. 

From just a few minutes of Google-ing, it looks like the `sqlite3` module doesn't provide a direct way to password protect the .db file on creation. Instead, an outside tool like [SQLCipher](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Encrypted-Databases) would have to be installed. I don't know if I exactly prefer this option because this would add another dependency.

**Comment by garlick** [comment]
My guess is UNIX file permissions are likely to be adequate here.

**Comment by cmoussa1** [comment]
Thanks for your input @garlick!

**Comment by dongahn** [comment]
@cmoussa1 and @garlick: I know @cmoussa1 also wanted regular users to inspect their accounting information. (read only). W/ UNIX file permission protection, will we give up on this capability? 

I am a big fan of simplicity and like the proposed protection scheme. But I thought we should at least discussion this.

**Comment by garlick** [comment]
If the idea is to have a user run a python script that directly access the database file, there is no way I know of to restrict access to specific records.  It would be all or nothing with UNIX file permissions.

I didn't look in detail, but sqlcypher is likely a layer that lets the db owner encrypt/decrypt db accesses on the fly, not a multi-user solution.

I would guess this would call for building a server in front of the database.  Users would authenticate to the server, and the server would broker access to the data.

**Comment by dongahn** [comment]
Since we can implement access control at flux module level, maybe we can introduce a thin flux module after all. It can fetch the accounting info directly from the DB or `flux-account` command per user's request and display the results. 

One simple control logic would be a normal user can only see his/her info (matching USER)?

**Comment by garlick** [comment]
There might be a way to do it more simply by configuring sudo to execute the `flux-account` script in such a way that it has access to the db file but is locked down from doing anything other than reading the invoking user's info...

(I apologize for not remembering your architecture here - I was picturing this db as disassociated from any flux instance but maybe that is not correct?)

**Comment by dongahn** [comment]
> There might be a way to do it more simply by configuring sudo to execute the flux-account script in such a way that it has access to the db file but is locked down from doing anything other than reading the invoking user's info...

Simpler the better at this point. By `sudo`, you mean using `setuid`'? (https://en.wikipedia.org/wiki/Setuid)

> (I apologize for not remembering your architecture here - I was picturing this db as disassociated from any flux instance but maybe that is not correct?)

Good comment. I was picturing this DB associated with the system instance. What is a use case of a nested instance accessing the user accounting DB? It seems not allowing nested instances to the centralized DB has many scalability advantages.  

@cmoussa1?

**Comment by garlick** [comment]
Doesn't the slurm accounting database reside on a system that is not part of any cluster, with limited access by users?

Anyway, I meant [sudoers(5)](https://linux.die.net/man/5/sudoers), and completely glossing over the details, the idea would be to allow users to run `sudo flux accounting args...` as a user/group with access to the db file, but somehow add an option or environment variable that causes it to internally restrict access to only the things you want a user to be able to do.

**Comment by cmoussa1** [comment]
> Good comment. I was picturing this DB associated with the system instance. What is a use case of a nested instance accessing the user accounting DB? It seems not allowing nested instances to the centralized DB has many scalability advantages.

This might be a naive point-of-view but I did not see the user accounting DB being of use in a nested instance. My vision for the user accounting DB would be something like the following:

As of now (and I think for at least the near future), the only information stored in this accounting database is the user and their ID, the account they can charge jobs against, a parent account, and some static user policy limits (which we talked about maybe not implementing as of now, which is OK). All of the user accounts that can submit jobs under Flux will be stored in the Accounting DB. This regulates who is allowed to submit jobs (e.g, when someone submits a request for an allocation, a check is performed to see if the user requesting an allocation has an account in this DB. If so, they receive their allocation and can run their jobs. If not, their request is denied). 

I don't see _much_ of a use case for users to want to interact with this DB if we don't implement the user policy limits (shares, max jobs, max wall time per job), so in my opinion it might be best if we restrict access to this DB to just the admins who need to interact with it directly (i.e adding and removing users, editing their account information).

**Comment by dongahn** [comment]
> Doesn't the slurm accounting database reside on a system that is not part of any cluster, with limited access by users?

I don't know the answer to this. But one advantage of this is admins can update accounting data to one database server. But disadvantages would be scalability and performance as it has to support access for each job submission across many cluster-wide system instances. 

Certainly for day one release, it seems to make sense to tie the database to a single flux system instance and see what admins think?

> limited access by users?

`sacct` does provide user-level access but only in limited mode as well.

**Comment by cmoussa1** [comment]
It feels like we came to a reasonable conclusion here that Unix file permissions would suffice for **FluxAccounting.db**, so I'll go ahead and close this issue. We can re-open if necessary.
