### ISSUE TITLE
view-bank: subcommand doesn't list users / children

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#184]
It would be useful if the 'flux account view-bank ...' command listed the child banks or users for a given bank to facilitate traversing the bank tree from the root.

**Comment by cmoussa1** [comment]
Yeah, looking at the code for the `view-bank` subcommand, I notice the SQLite query returning the bank information _just_ looks at the bank passed in, and not any sub banks or children of that bank. 

(sort of speaking to myself here so I don't forget later) I believe that work will involve adding additional queries to find any additional banks where the bank passed in is a `parent_bank`; this should allow to find any child banks. 

```sql
SELECT * FROM bank_table WHERE parent_bank=passed_in_bank;
```

As for listing users, I think I can leverage the work done in the `view-user` subcommand to fetch user information for a given leaf bank.
