### ISSUE TITLE
create_db.py: make file path to database configurable 

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#20]
**create_db.py**, the script responsible for creating the database file and the table inside the database, does not take any file path arguments. This means that when this script is called, the .db file (**FluxAccounting.db**) gets placed in the same directory:

```
.
|-- AUTHORS
|-- CONTRIBUTING.md
|-- COPYING
|-- LICENSE -> COPYING
|-- Makefile
|-- NOTICE -> NOTICE.LLNS
|-- NOTICE.LLNS
|-- README.md
|-- accounting
|   |-- FluxAccounting.db
|   |-- __init__.py
|   |-- accounting_cli.py
|   |-- accounting_cli_functions.py
|   |-- create_db.py
```

This is because of the `sqlite3.connect()` line in **create_db.py**, which takes a filepath string as an argument:

```python
conn = sqlite3.connect(filepath)
```

which, for now, is just set to the same directory as **create_db.py**:

```python
def main():
    create_db("FluxAccounting.db")
```

From talks with @SteVwonder, this functionality probably needs to undergo a couple of changes:

- the database file probably needs to created in a different location, one that can be specified by the user when they call this script. Probably something like the following:

```
$ ./create_db.py path/to/db
```

This change will _also_ need to be reflected in `accounting_cli.py`, because it establishes a connection to the .db file when it is called with any of the subcommands (`add-user`, `edit-user`, etc.). 

Maybe a strategy to accomplish this is to create a subcommand for _both_ scripts to set the .db file location? 

```
$ ./create_db.py set-db-location --filepath=/path/to/db
$ flux account set-db-location --filepath=/path/to/db
```

- the commands that make a connection to/interact with the database probably need a failsafe of some kind in case it does not establish a connection to the database. If it doesn't, the sqlite3 API will default to creating an empty .db file, which is no good. I think a workaround for this would be to interpret the database as a URI; this way, we can specify _only_ enable read/write mode for the subcommands [[1]](https://docs.python.org/3.7/library/sqlite3.html#sqlite3.connect). 

```python
conn = sqlite3.connect('file:path/to/db?mode=rw', uri=True)
```

**Comment by cmoussa1** [comment]
One thing I think I need to keep in mind:

In flux-accounting's current structure, the accounting DB is _created_ in one script (`create_db.py`), 
and the DB is _interacted_ with in another script (`accounting_cli.py`). So the path to the .db file will have to be configured in both scripts. I'm thinking of ways to establish the same path in both scripts so that they are pointing to the same database after it's been created (wherever that location may be).

---

For `create_db.py`, this could be relatively straightforward - just create one subcommand that will create the database file in a desired location:

```python
def create_db(filepath):
    # open connection to database
    logging.info("Creating Flux Accounting DB")
    conn = sqlite3.connect("file:" + filepath + "?mode:rwc", uri=True)

.
. 
.

def main():
    subparser_set_db_path = subparsers.add_parser(
        "set-db-path", help="Set database file location"
    )
    subparser_set_db_path.set_defaults(func="set_db_path")
    subparser_set_db_path.add_argument("path", help="path", metavar=("PATH"))

    args = parser.parse_args()

    try:
        if args.func == "set_db_path":
            create_db(args.path)

    create_db(args.path)
```

---

In `accounting_cli.py`, the path to the .db file will need to be configured before running any of the other subcommands (adding/removing/editing a user) since the commands will be interacting with the database directly. One route would be to have the path also be specified when running any one of the subcommands:

```
$ flux account path/to/db view-user fluxuser
```

However, I am wondering if there is a more permanent way to configure the .db file path for the subcommands without having to actually go into the `accounting_cli.py` file and change the line of code that establishes the connection to the database:

```python
conn = sqlite3.connect("FluxAccounting.db")
```

**Comment by SteVwonder** [comment]
> In accounting_cli.py, the path to the .db file will need to be configured before running any of the other subcommands (adding/removing/editing a user) since the commands will be interacting with the database directly. One route would be to have the path also be specified when running any one of the subcommands:

I think that makes sense.  My only suggestion would be to make it an optional argument through a flag.  For example, if `-d` was the chosen short arg (not sure if that's the right letter, just a strawman): `flux account -d path/to/db view-user fluxuser` and then if the user doesn't provide that path, just fall back to some hardcoded default (e.g., `FluxAccounting.db` in the current directory).  Later on, maybe that default can be to read the config files for the enclosing flux instance and look for a database path there.
