### ISSUE TITLE
job-archive interface: only query jobs for a specific user/bank combo

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#218]
In an offline discussion with @ryanday36, he reported that job usage values were updated for all rows of a user in the `association_table` even when jobs were only submitted under one bank.

I am pretty sure this is because in the `calc_usage_factor()` function, `SELECT` statement simply fetches all jobs under a specific user instead of a user/bank combination:

```sql
SELECT userid,id,t_submit,t_run,t_inactive,ranks,R FROM jobs WHERE userid=?
```

The job-archive interface needs to be edited to only query and count jobs from a specific user/bank combo.

**Comment by ryanday36** [comment]
This might be an implementation detail, but I would add that if no bank is specified for the job, then the job-archive interface should use the default bank.
