### ISSUE TITLE
add "project" support

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#247]
I will probably add more specific sub-issues once I get more information on what is required and how WCKey support is supposed to be implemented, but I wanted to just make a note for now that flux-accounting will need to support workload characterization keys (WCKeys for short) for users in a flux-accounting database. My notes so far consist of the following:

WCKeys allow users from different banks to all work on the same project instead of creating a new bank and adding a bunch of users to it. This WCKey is specified on job submission with, but if not specified, it will use the user’s default WCKey for the cluster. On the job record for a user’s job, the record will be appended with an asterisk (*) to show that the user used their default WCKey.

**Comment by garlick** [comment]
Here's the slurm documentation for wckey:  https://slurm.schedmd.com/wckey.html

If I understand correctly, resource utilization reports can now be generated per user or per bank, and this adds another way to group users arbitrarily and report the group's resource utilization?

Would it be more natural to call this something like a "project" or "team" or even a "group"?

**Comment by ryanday36** [comment]
It sounds like you all are on it. The idea is to be able to group jobs / users for reporting purposes in a way that is independent of their bank / priority. So, it shouldn't be included in or affect fairshare. I see it as more of a way to be able to set a bit of metadata in the accounting db that will be attached to all of a user's jobs unless they specify a different value for that metadata when they submit. Also, yes, calling them 'projects' is perfectly reasonable and a lot less clunky than 'workload characterization keys'.

**Comment by ryanday36** [comment]
> * a user can be a member of multiple projects

True. A user can be a member of multiple projects, with one of them being the user's default project.

> * jobs submitted with an unknown project are rejected

False. A user may run on a cluster even if they are not a member of a project.

> * jobs submitted without a project are not charged to a project

True. Although WCI does tend to want to assign users to a project after the fact if the user has a lot of usage in a given reporting period.

**Comment by ryanday36** [comment]
> I guess I was trying to nail down what happens at submit time if I specify an invalid project name (as opposed to leaving the project out entirely). Shouldn't it be rejected in case the user just typed it wrong?
> 
> A follow on question would be what happens if I specify a valid project that I'm not a member of?
> 
> I was assuming that the accounting db would track all valid project names and their user membership, but maybe this is intended to be looser than that.

Gotcha. I misunderstood. Yes, jobs where a user specifies an invalid project or a project that they're not a member of should probably be rejected.

**Comment by garlick** [comment]
Linking flux-framework/flux-core#3257

Oh look we already renamed it to "project" two years ago :-)

**Comment by cmoussa1** [comment]
Lots of good conversation in this thread, so I think I'll begin opening some smaller, more specific sub-issues to start tackling this week. :-)

**Comment by cmoussa1** [comment]
There are more specific issues open in regards to project support in flux-accounting now, so I think I'll close this issue.
