### ISSUE TITLE
docs: update and create more in-depth flux-accounting documentation

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#259]
A great suggestion was brought up in a team meeting last week about creating some more in depth documentation about configuring and using flux-accounting for our admins and perhaps creating a set of documentation pages similar to flux-core's ReadTheDocs site. The information on these pages could include some of the following, just to name a few:

- basic flux-accounting administration
  - adding/removing/editing users and banks
  - looking at usage and fairshare information for users
- job usage and fairshare documentation
  - examples of how usage is calculated
- multi-factor priority plugin
  - what factors are used, how they affect job priority calculation
  - accounting limits (`max_active_jobs`, `max_running_jobs`)

Feel free to add additional pieces of documentation we'd like to see or if there are any suggestions or changes we'd like to see to the ideas posted above.

**Comment by garlick** [comment]
Does the [flux accounting guide](https://flux-framework.readthedocs.io/en/latest/guides/accounting-guide.html#database-administration) resolve this issue?

Maybe this could be closed and further issues opened in flux-docs?

**Comment by cmoussa1** [comment]
I think it does, thanks for pointing it out; I'll close the issue and re-open any other future issues in flux-docs.
