### ISSUE TITLE
feedback on 'flux account ...' command

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#29]
1. it appears that user names currently have to be unique. We often have one user with multiple banks (accounts), so we’ll need the ability to create multiple users with the same username.
2. account names are unique in Slurm, so we generally don’t need to specify the parent account when adding a user (though we do need to specify a parent when adding a new account). I don’t think that we want the parent account to be a required field in add-user. More generally, it’d be nice to have default values for several of the add-user options (e.g. admin-level=user --shares=1).

**Comment by dongahn** [comment]
Thanks @ryanday36. Our strategy is to make the users of flux account happy for is interface first and then work our way into the integration. 

Could you look at the last PR https://github.com/flux-framework/flux-accounting/pull/26. I think @cmoussa1 specifically added this change to address your feedback at #2. 

@cmoussa1: we don't have a patch for #1 yet?

**Comment by ryanday36** [comment]
Yes. It looks like PR #26 addresses my feedback about default values.

**Comment by cmoussa1** [comment]
Thanks @dongahn and @ryanday36! 

> 2. account names are unique in Slurm, so we generally don’t need to specify the parent account when adding a user (though we do need to specify a parent when adding a new account). I don’t think that we want the parent account to be a required field in add-user. More generally, it’d be nice to have default values for several of the add-user options (e.g. admin-level=user --shares=1).

Yes, I believe #26 should address the feedback concerning default arg values when creating accounts using `add-user`.

> 1. it appears that user names currently have to be unique. We often have one user with multiple banks (accounts), so we’ll need the ability to create multiple users with the same username.

PR #25 I hope should address the feedback there. That removed the `UNIQUE` constraint when creating users, so you should be able to create a user with multiple accounts.

**Comment by cmoussa1** [comment]
I think this issue can be closed since PR #25 and #26 addressed this feedback - if not, I can always re-open. :-)

**Comment by dongahn** [comment]
Thanks @cmoussa1.

@ryanday36: let me know what you think. I believe our next priority should be https://github.com/flux-framework/flux-accounting/issues/30. Do you agree?
