### ISSUE TITLE
[docs portal] repository needs tags!

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-accounting#305]
See 
![image](https://user-images.githubusercontent.com/814322/210154697-e9d73511-867c-414c-bf17-5685e339a664.png)

When they are added here they will show up there (the next day).

**Comment by cmoussa1** [comment]
Great suggestion, and I'm sorry there were no tags for this repository in the first place! I believe I've successfully added some to the home page for this repository:

![image](https://user-images.githubusercontent.com/20131404/210624965-ca1f3308-9182-4363-a68f-400f9b50cf52.png)

Perhaps we should keep this issue open until we confirm that the tags show up the next day.

**Comment by vsoch** [comment]
woot! Thank you @cmoussa1! Those should appear after the automation tonight. Closing issue, resolved!

**Comment by vsoch** [comment]
Oops and I see your note - I'll check tomorrow and re-open if they aren't there. The action has run fairly reliably so I think it should work https://github.com/flux-framework/flux-framework.github.io/actions/workflows/update-data.yaml (but good idea to check).

**Comment by cmoussa1** [comment]
Sounds great!

**Comment by cmoussa1** [comment]
Just to follow up on this, looks like the tags showed up on the Flux website!

![image](https://user-images.githubusercontent.com/20131404/210824694-706cef14-635e-48c9-89b6-e0b1f98b16da.png)

Thanks again for suggesting this @vsoch!! :D

**Comment by vsoch** [comment]
Haha sure thing! I also checked this morning - there is a tiny overlap with the logo that warrant some padding but I’ll fix that up in a future PR. Thanks for adding these @cmoussa1 !
