### ISSUE TITLE
FluxAccounting.db: need a table to describe bank/account hierarchy

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#32]
As discussed earlier this week, a new table describing bank and account information should be added to **FluxAccounting.db**, the database file storing user account information. 

Currently, the lone table in this database, `association_table`, has a column labeled `account` and an optional `parent_acct` for every user that gets added to this database. 

```
account       tinytext   NOT NULL
parent_acct   tinytext   NOT NULL
```

But the `account` column itself does not have any bank amounts or information itself. We could probably describe this by creating a new table, maybe called `bank_table`:

```
CREATE TABLE IF NOT EXISTS bank_table (
    account_name        text    NOT NULL,
    parent_acct_name    text,
    shares              int     NOT NULL,
    PRIMARY_KEY(account_name)
);
```

I believe creating a bank table would actually remove the need to have a `parent_acct` field in `association_table`, since that information would instead be stored in the bank table. This would also give us the ability to describe a bank/account hierarchy, similar to the usage files @ryanday36 has shared with us:

```
Account       | User   | 
root          |        |         
 root         | root   |  
 account_1    |        |  
  subacct_1   |        |  
  subacct_2   |        |  
   subacct_2_1| user1  |  
   subacct_2_2| user2  |  
  subacct_3   |        | 
```

_note that there is no usage data as of yet, as we still have to implement usage calculation per user and per account. This would probably be a next step after the creation of a bank/account table._

The three fields, `account_name, parent_acct_name, shares`, are the ones I can think of that could give some baseline functionality to creating a bank hierarchy. Can you think of any other fields that might be needed? @ryanday36

**Comment by dongahn** [comment]
@cmoussa1: 

I think you may want to consider actual SQL queries in mind in designing the schema further.  If you want to create a full bank/accounting hierarchy like we discussed with @ryanday36, what would be typical SQL queries you would need? 

Would it be mainly a Join operation? Like join the `association_table` with `bank_table`? How would you join those two? What would be a foreign key?

If you need to dump the entire bank table info into the internal tree of bank hierarchy in memory, what SQL queries and how many of those will be needed?

**Comment by ryanday36** [comment]
> The three fields, account_name, parent_acct_name, shares, are the ones I can think of that could give some baseline functionality to creating a bank hierarchy. Can you think of any other fields that might be needed?

Those three fields should be enough to build a bank hierarchy. One other thing that I'm curious about, do you see this as being one database per cluster, or a centralized database for multiple clusters? There's arguments both ways, but if it's the latter will there be an association table for each cluster (<clustername>_association_table) or a field for cluster name?

**Comment by cmoussa1** [comment]
> Would it be mainly a Join operation? Like join the association_table with bank_table? How would you join those two? What would be a foreign key?

That's what I was thinking - a `JOIN` between `association_table` and `bank_table`. To create the hierarchy, we could join based on the account name, since that would be present in both tables. 

> One other thing that I'm curious about, do you see this as being one database per cluster, or a centralized database for multiple clusters? There's arguments both ways, but if it's the latter will there be an association table for each cluster (_association_table) or a field for cluster name?

Good question. I was thinking this being one database per cluster - the `association_table` would list the users registered on the cluster, and the `bank_table` could list the breakdown of the accounts registered on that same cluster. Does this seem reasonable?

**Comment by dongahn** [comment]
> That's what I was thinking - a JOIN between association_table and bank_table. To create the hierarchy, we could join based on the account name, since that would be present in both tables.

I think a requirement expressed from @ryanday36 is that a user can belong to multiple banks. How do you plan to support this?

**Comment by cmoussa1** [comment]
The primary key for `association_table` is a combination of both `username` and `account`. This should allow multiple entries for associations with the same username that can belong to multiple banks.

**Comment by ryanday36** [comment]
I think one database per cluster is reasonable, and probably the best way to do things, especially at first. In some senses it's more to maintain than a centralized database, but it sounds like the database is going to be pretty integral to fairshare job scheduling, so having a database per cluster removes a central point of failure that can take out all of the clusters.
