### ISSUE TITLE
avoid jobs getting stuck in PRIORITY state

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#335]
When a job is submitted and an otherwise valid user has no bank information, the job gets stuck in the `PRIOIRTY` state, presumably waiting for a future accounting update that includes bank information for that user.

The reason for the PRIORITY state is that a priority plugin may have its information asynchronously updated, and we do not want to reject all jobs when the plugin is not yet ready to calculate a priority. Unfortunately, there is no good way to tell if the user will _ever_ be added to a bank or if the plugin will be updated momentarily with that user's information.

@garlick proposed that the accounting mf_priority plugin reject jobs whose priority would not be able to be calculated in the `job.validate` callback. Then, the plugin could include a helpful message like "You are not currently a member of any bank", or whatever message is appropriate.

I had actually forgotten that `job.validate` is not called for jobs during restart (it is assumed already ingested are valid), so this approach has little risk of rejecting all jobs after a restart or plugin reload - though of course this should be well tested.

The plugin should _not_ reject jobs if it has no data about any users. In this case the plugin may not have had the first accounting update sent. In this case the job(s) should remain in the PRIORITY state.

The other alternative here would be a validator plugin which contacts the accounting service to see if a user is valid. There are complaints that this would be too heavyweight, however, it could be implemented out-of-tree, enabled on a per-system basis, and would only affect the system instance. It would also avoid rejecting jobs from users that are in the database, but have not yet reached the accounting plugin. The existing feasibility plugin also sends an RPC to the scheduler and all feasibility plugins run in parallel, so the impact could be minimal. It would be very simple to test.

**Comment by cmoussa1** [comment]
This issue was pretty relevant to #346 and was addressed by the changes made by #347, so I think we can close this too. I can always re-open in case we want to have further discussions about how the plugin addresses handling jobs from new users or users who don't yet have a bank.
