### ISSUE TITLE
systemd: use `BindTo=flux.service` instead of `Requires=flux.service`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#337]
When upgrading a system to the latest flux-core, we noticed that flux was unexpectedly restarted by systemd, even after shutdown caused the broker to exit with the special exit code 42 defined in `RestartPreventExitStatus=42` (See flux-framework/flux-core#5072).

Through some debugging, @garlick was able to determine that the reason flux was restarted by systemd was because it is mentioned as a `Requires` by `flux-accounting`, which has `Restart=always`.

We found that if `Requires` is replaced with `BindsTo`, then things work more as expected, i.e. if flux is shutdown, then flux-accounting is also, and similarly when flux is started,  the flux-accounting service is started.

Let's make this change in the `flux-accounting.service` and get it into the next TOSS 4 release, since auto-restarting flux when the admins don't expect it will be frustrating.

If you do not want to generate a whole release for this small change, we can also apply a patch in the RPM specfile. Up to you @cmoussa1.

**Comment by cmoussa1** [comment]
I can see how that might be frustrating! Thanks for catching this and sorry that it was causing some unwanted behavior. I can take care of this today. I'll post a PR shortly that changes `Requires` to `BindsTo` and then re-release and build RPMs. It shouldn't take too long for flux-accounting. 🙂

**Comment by garlick** [comment]
No worries!  This was a learning experience for @grondo and me too.
