### ISSUE TITLE
reject jobs from users with no bank

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-accounting#346]
Can we set up the flux accounting job tap plugin to reject jobs from users with no bank and print a helpful error message (e.g. 'no bank found for user ...')? @grondo also suggested that the plugin should only reject jobs if it has data for some users. i.e. if there's no data for any users, we probably don't want to reject jobs, but if there are users who have banks, we probably do want to reject jobs from users who don't have banks.

**Comment by cmoussa1** [comment]
No problem! I'll get to work on this.

**Comment by cmoussa1** [comment]
This should be fixed by #347, so I'll go ahead and close this for now.
