### ISSUE TITLE
mf_priority: audit plugin `job.validate` callback for job updates

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#376]
Now that Flux supports updates of select job attributes, we should audit the multifactor priority plugin use of the `job.validate` callback to ensure it will work with job _update_ validation too.

When a user makes a job update request, the attribute updates must first be _allowed_ by a jobtap plugin matching the callback `job.update.attributes.system.ATTR` for example, then the updates are _validated_ by calling the `job.validate` plugin stack with a proposed jobspec.

This perhaps breaks an assumption in existing plugins that `job.validate` is only called for newly submitted jobs.

For example, at the end of `validate_cb()` in `mf_priority.cpp`, the callback returns an error if the user has met or exceeded the number of active jobs:

https://github.com/flux-framework/flux-accounting/blob/23edc84692aa13b4f514423ae42d623e9db92c19/src/plugins/mf_priority.cpp#L754-L758

This assumes that the job being validated is a proposed new job and not an update to an existing job. From a quick perusal this appears to be the only spot that might need to be protected by a check for the state of the proposed job, i.e. only make this check if the job state is `FLUX_JOB_STATE_NEW`.

However, the function should be carefully audited to ensure this is the only place that might be affected by calling `job.validate` multiple times on the same job, and we should add some testing of job updates in the flux-accounting testsuite -- especially for corner cases such as: a user is at the active job limit and they are successfully able to update the duration of a pending job.

**Comment by cmoussa1** [comment]
Thanks for letting me know @grondo. I can take a look at this and get working on it. If it's helpful at all, here is everything step-by-step that `validate_cb ()` currently checks in the priority plugin, just in case there is anything else that might need to be moved:

1. the plugin performs a search of its internal map to see if it has any information about the user that submitted the job - if the plugin has information **but not for the user that submitted the job**, it will be rejected.
2. the plugin checks that if the user submitted their job under a specific bank, that the user is **allowed** to submit under that bank, i.e it checks that the user has an entry under said bank in the plugin's internal map. If not, it will be rejected. If the user is submitting under a default bank, it will check that the user **has** an entry in the plugin's internal map under a default bank. If not, it will also be rejected.
3. if the user/bank has been disabled (i.e their `active` status is set to 0), their job will be rejected.
4. if the user/bank passed in a specific queue, it will check that the user has permission to submit jobs under this queue. If not, their job will be rejected.
5. the callback checks the user/bank's active jobs limit. If the user/bank is currently at their limit, their job will be rejected (this is the one you already pointed out!).

> From a quick perusal this appears to be the only spot that might need to be protected by a check for the state of the proposed job, i.e. only make this check if the job state is `FLUX_JOB_STATE_NEW`.

Sorry in advance if I am misunderstanding you, but are you suggesting that this check for the active jobs limit be moved to  `new_cb()`, the callback that handles jobs that are in `job.new`?

**Comment by grondo** [comment]
Yeah, 1-4 sound like they will work even for a job update. If the bank or queue hasn't changed, then the job update should _not_ be rejected since nothing has changed, but if we do allow bank or queue updates these will reject an update of a queue or bank to an invalid or inactive one.

> Sorry in advance if I am misunderstanding you, but are you suggesting that this check for the active jobs limit be moved to new_cb(), the callback that handles jobs that are in job.new?

No, I think what you can do here is only make the final check (number `5` in your list above) if the job is in the NEW state, e.g. unpack the current job state from the plugin args and then check that the state is `FLUX_JOB_STATE_NEW` before checking max_active_jobs, e.g. something like:

```diff
diff --git a/src/plugins/mf_priority.cpp b/src/plugins/mf_priority.cpp
index 0870431..a0714a6 100644
--- a/src/plugins/mf_priority.cpp
+++ b/src/plugins/mf_priority.cpp
@@ -962,7 +962,9 @@ static int validate_cb (flux_plugin_t *p,
 
     // if a user/bank has reached their max_active_jobs limit, subsequently
     // submitted jobs will be rejected
-    if (max_active_jobs > 0 && cur_active_jobs >= max_active_jobs)
+    if (state == FLUX_JOB_STATE_NEW
+        && max_active_jobs > 0
+        && cur_active_jobs >= max_active_jobs)
         return flux_jobtap_reject_job (p, args, "user has max active jobs");
```

**Comment by grondo** [comment]
One other thing, after a `job-update` event is posted a new `job.update` callback is invoked by the job manager. The `mf_priority` plugin may need to have a callback for this event in the case that `bank`, `project` or `queue` are updated, i.e. it might no longer be the case that these job attributes are static for the lifetime of a job.

I haven't checked, but you might be able to just move a subset of the work done in `job.new` to a new function that is called by both `job.new` and `job.update`... Do you want a separate issue opened on this one?

**Comment by cmoussa1** [comment]
> I haven't checked, but you might be able to just move a subset of the work done in `job.new` to a new function that is called by both `job.new` and `job.update`... Do you want a separate issue opened on this one?

Sure, that might be a good idea to open a separate issue.

**Comment by grondo** [comment]
> Ah, okay, thanks. How does the state variable get unpacked? Does that get unpacked within flux_plugin_arg_unpack () along with the other job attributes?

Yes, it is unpacked via the `state` parameter, e.g. the `limit-duration` plugin does that here:

https://github.com/flux-framework/flux-core/blob/714a33f1db9bfb253c58b45812844b0559edbfa7/src/modules/job-manager/plugins/limit-duration.c#L217-L243

**Comment by cmoussa1** [comment]
Closing this now that #378 has landed.
