### ISSUE TITLE
create_db.py: add error handling for failed DB creation

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#38]
As mentioned in the comments in #36, there is no error-handling the `create_db` function. Even if the database fails to be created, there will be no error message or return code. We'll need to add some output in case the database fails to get created.

**Comment by dongahn** [comment]
> We'll need to add some output in case the database fails to get created.

Yes. And you would also need to be able to propagate any failure as the exit code from flux account create-db. Normally, exit with the return code of 1 with some reasonable logging of error messages will do.

**Comment by cmoussa1** [comment]
I'll go ahead and add here that error propagation should be added for multiple subcommands (as noted in #34, some of the bank subcommands will need to undergo this change as well). This will be future work following this most recent milestone.
