### ISSUE TITLE
support bank and project updates

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-accounting#391]
Now that the job manager has an update service, all that is required to support `flux update JOBID bank=BANK` and `flux update JOBID project=PROJECT` would be to add  `job.update.attributes.system.bank` and `job.update.attributes.system.project` handlers in the priority plugin. These handlers just need to check that the update is valid for the requesting user, then this will result in the `jobspec-update` event and an eventual call to the `job.update` event.

**Comment by cmoussa1** [comment]
This is now supported after #377, so I can close this. Will re-open if more specific issues arise. 👍
