### ISSUE TITLE
the flux user cannot run jobs when flux-accounting is installed and flux is not in the database

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#476]
Problem: It seems like the `flux`(instance owner) user should always be allowed to run, to support "system jobs".  (@jameshcorbett has a use case for this now).  But flux-accounting prevents this unless the flux user is in the database.

I was thinking maybe flux-core could do something to ensure this always works but I'm not sure how we would do that generally - it might need to go in flux-accounting.  But anyway,  maybe others have some ideas.

**Comment by grondo** [comment]
Sounds like a good idea to me! You should be able to check the `security.owner` broker attribute, or just use `getuid(2)` to get the userid of the instance owner (it need not always be user `flux`).

**Comment by cmoussa1** [comment]
Cool, thanks! I think I'm able to get the userid no problem by just checking the `security.broker` attribute. Is there a way to fetch the name of the instance owner, then, if it is not always `flux`?

**Comment by cmoussa1** [comment]
Oh, duh. I just realized if I have the UID I can just look up the corresponding username:

```
pwd.getpwuid(int(userid))
```

**Comment by grondo** [comment]
Hm, you may have to use `getpwuid_r(3)`, but let me see if somewhere else in flux already has this information.
