### ISSUE TITLE
documentation links are inconsistent

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-accounting#507]
Problem:  I noticed the following inconsistency in the way framework project docs are represented.  We should probably try to be uniform.

**flux-core**
https://flux-framework.readthedocs.io/projects/flux-core/en/latest/index.html (works)
https://flux-core.readthedocs.io/en/latest/index.html (redirects to above)

**flux-accounting**
https://flux-framework.readthedocs.io/projects/flux-accounting/en/latest/index.html (dead link)
https://flux-accounting.readthedocs.io/en/latest/guide/accounting-guide.html (works)

I did not try to figure out why this is - just noticed it and wanted to get an issue open.

**Comment by cmoussa1** [comment]
It looks like on the ReadTheDocs project page for https://flux-framework.readthedocs.io/projects/ there is a "sub-projects" section if you click on the blue down arrow in the top-right of the project window: https://app.readthedocs.org/projects/flux-framework/. I don't think I am listed as a maintainer on there right now? If you could add me, perhaps I could add flux-accounting as a "sub-project" - maybe there is some configuration there where I can set up some redirects.

**Comment by cmoussa1** [comment]
Ah, looks like there is a setting under the project page where you can add Subprojects, where it states:

> Subprojects are projects hosted from the same URL as their parent project. This is useful for organizing multiple projects under a custom domain.

Perhaps we want to add flux-accounting here as a subproject. I'm not sure who manages maintainer access to the flux-docs project page on ReadTheDocs though; I don't think I'm able to access the project settings for flux-docs at the moment?

**Comment by garlick** [comment]
Hmm, yeah over here I see rfc, core, security, and sched but not accounting:

https://app.readthedocs.org/dashboard/flux-framework/subprojects/

I don't see  how to give your user the same capabilities as me.  Maybe @vsoch can do that?  And maybe since I'm bumbling around clueless she will have a better idea of what we need to do?

**Comment by grondo** [comment]
I think you can add projects and maintainers on the readthedocs.org dashboard:

https://readthedocs.org/dashboard/flux-framework/users/

**Comment by cmoussa1** [comment]
Thanks @grondo! It looks like I don't have access to the "Admin" page on the flux-framework page on ReadTheDocs, so I can't add myself as a maintainer there. I can see the "Admin" page on flux-accounting, FWIW.

**Comment by grondo** [comment]
I'll add your llnl address. Though one problem may be that flux-accounting should be imported as part of flux-framework and not on its own?

**Comment by garlick** [comment]
Oh I see - I'll just add Chris.  Thanks!

**Comment by cmoussa1** [comment]
Looks like the dead link you reported is working now! Can you confirm on your end?

**Comment by garlick** [comment]
Yep it is working for me!
