### ISSUE TITLE
idea: implement format string for some of the `view-*` commands

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#519]
Some great feedback given in #514 was to perhaps replicate flux-core's use of a format string when viewing data so that the user can customize the fields when looking at certain data, especially if it has many columns, like the `association_table` in the flux-accounting DB.

**Comment by grondo** [comment]
If it is helpful, there's examples of how to subclass the `flux.util.OutputFormat` class to easily add a `-o, --format` option to a command in the flux-core codebase.

The simplest example might be the [HKFormat](https://github.com/flux-framework/flux-core/blob/e0ab98852d1559c483f844e3e0cf7989a6179c70/src/cmd/flux-housekeeping.py#L50-L74) class in `flux-housekeeping.py`

Note also the subclass of `UtilConfig` used to store a couple default formats. This also allows users to register their own formats by name in system-wide or per-user config files

**Comment by cmoussa1** [comment]
flux-accounting now has its own `AccountingFormatter` class with some common utility for printing out the results of a SQL query in both JSON or table format, so I'll go ahead and close this issue. I'll re-open more specific issues if they come up in the future.
