### ISSUE TITLE
job_archive_interface: implement job usage calculation

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#58]
Okay, now that #57 has landed and the job-archive interface functions are their own module, we can move on and start to extend this module's functionality beyond just job record listing. 

We discussed last week about this module playing a part in some of the "internal" work for fair share calculation. Although the static information comes directly from the flux-accounting database (user account information and bank information), this specific module (which interacts with flux-core's job-archive module) can fetch information pertaining to job history and calculate the usage factor in fair share. 

#### Slurm's definition of usage

If we wanted to calculate job usage according to Slurm's definition, it would be the following:

```
U_normalized = U_user / U_total
```

where: 

> `U_user` is the processor * seconds consumed by all of a user's jobs in a given account for over a fixed time period and `U_total` is the total number of processor * seconds utilized across the cluster during that same time period. 

So, I _think_ this would entail fetching job records for some user _U_, summing up the number of cores and multiplying it by `t_elapsed` across those same jobs, and dividing it by the number of cores * `t_elapsed` across all job records in the job-archive.  To only take the jobs that have completed in the past _x_ minutes, we can add another filter to fetching job records to only fetch jobs that have completed after some certain time _t_ (this could probably help represent the _decay factor_  in calculating job usage, where more recent jobs weigh heavier than older jobs). 

One note I thought of that I think we should keep in mind: in another issue thread, @ryanday36 made this good comment about charging usage:

> Accounting by total number of cores works fine as long as users get charged for all of the cores when we give them a whole node. i.e., in slurm, a user can run something like 'srun -n1 ...' and only ask for 1 task on one core, but, on most of our clusters, we're giving them the whole node anyway, so we need to charge them for all 36 (or whatever) cores.

So, if I am understanding this correctly, that means even if a user submits a job with the following job spec:

```bash
> flux mini submit -n 1 hostname
```

this would mean we would need to charge for the whole node when performing the usage calculation, right? If that's the case, would our usage calculation instead become a product of the total `num_nodes` and `t_elapsed` across a user's jobs? 

FWIW, I submitted two jobs in the `fluxorama` Docker container:

```bash
> [fluxuser@d215a637d63f flux-ba]$ flux mini submit -n 1 hostname
ƒAXNoQrj
> [fluxuser@d215a637d63f flux-ba]$ flux mini submit -N 1 hostname
ƒD3dvZMq
```

and the result of their two job specs are fairly similar:

```json
ƒAXNoQrj

[
  {
    "type": "slot",
    "count": 1,
    "with": [
      {
        "type": "core",
        "count": 1
      }
    ],
    "label": "task"
  }
]
```

```json
ƒD3dvZMq

[
  {
    "type": "node",
    "count": 1,
    "with": [
      {
        "type": "slot",
        "count": 1,
        "with": [
          {
            "type": "core",
            "count": 1
          }
        ],
        "label": "task"
      }
    ]
  }
]
```

So I could probably re-use the  `count_ranks()` helper function to count the number of nodes for a users' jobs and the `t_elapsed` property for all of the job records. And, from speaking with @chu11, to get a core count from a node, we'd have to look up node hardware info, which isn't stored in a job's `R` as of now.

So, maybe to start, I can calculate a usage factor based on `nnodes` * `t_elapsed`, and then adjust if we need to instead calculate a precise number of cores.

**Comment by ryanday36** [comment]
Just to fully and properly complicate this, as we run things now, most of our clusters are node scheduled, so usage should be calculated based on nnodes (or ncores if all of the cores are assigned to the users job regardless of -n). Some of them are core scheduled, so usage should be based on ncores for those. We also have one cluster (so far) where pbatch is node scheduled and pdebug is core scheduled. I think we could just get away with treating that one as node scheduled though.

**Comment by cmoussa1** [comment]
Thanks @ryanday36! Maybe as a first pass, I was thinking I would start with calculating usage just based on `nnodes`. Then, once that becomes stable, I can add additional capability to calculate usage based on `ncores`. Off the top of my head, I don't _think_ there is much of a difference in the calculations itself, just in the fields used to perform said calculation.

**Comment by ryanday36** [comment]
Sounds like a good plan @cmoussa1.

**Comment by cmoussa1** [comment]
The other major part needed for job usage calculation would be the decay of past jobs when recalculating a new usage factor. It looks like there are three variables that determine how jobs decay as they get older:

**PriorityDecayHalfLife**: determines the contribution of historical usage on the composite usage value. The larger this number is, the longer past usage affects fair share. The default is 7 days (604,800 seconds).

**PriorityCalcPeriod**: the period of time in which the half-life decay will be recalculated. The default is five minutes.

**PriorityUsageResetPeriod**: the time at which past usage information gets reset to 0. The default is to never do this, but can be configured to run daily, monthly, quarterly, yearly, etc. 

To summarize, I think this means that every **PriorityCalcPeriod**, a new historical usage factor is calculated based on jobs that have completed in the past **PriorityDecayHalfLife**. Every **PriorityCalcPeriod**, it will essentially say "give me all jobs that have completed in the past **PriorityDecayHalfLife** period, and I will recalculate the new usage factor."

I am trying to picture how past **PriorityDecayHalfLife** period values would be stored, and if I am remembering correctly from our meeting last week, we could store these values in another table in the flux-accounting database, where each row is an entry for a user's job usage factors, and the columns hold the past usage factor values:

| user | U_last_period | U_period_2 | U_period_3 | ... |
| ---- | -------------- | ----------- | ----------- | -- |
| user1 | value1 | value2 | value3 | ... |
| user2 | value1 | value2 | value3 | ... |
| ... |

Where the amount of columns goes up to the period of time where jobs no longer count towards generating a new usage factor (**PriorityUsageResetPeriod**: instead of never clearing older jobs, we can set this to every month, or every quarter or something). 

For example, if **PriorityUsageResetPeriod** was set to 4 weeks, and **PriorityDecayHalfLife** was set to 7 days, I think our table would look like the following:

| user | U_1_week_ago | U_2_weeks_ago | U_3_weeks_ago | U_4_weeks_ago |
| ---- | -------------- | ---------------- | --------------- | --------------- |
| user1 | value1 | value2 | value3 | value4 |
| user2 | value1 | value2 | value3 | value4 |
| ... |

We could then store the _current_ usage factor for a particular user in the `association_table`; this value would get updated every **PriorityCalcPeriod**.

This is just a rough draft of my version of implementing this, however - things can change and it might turn out that this won't be the best strategy.

**Comment by cmoussa1** [comment]
I think we could also create a table with a configurable amount of columns by using the `ALTER TABLE` statement: 

```sql
ALTER TABLE table_name ADD COLUMN column_definition;
```

One thought on how we could implement this is the amount of columns could be set as an option when initially creating the database (via the `flux account create-db` command)
