### ISSUE TITLE
Weighted tree library

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-accounting#63]
@cmoussa1, @SteVwonder, @ryanday36 and @garlick chatted about this at yesterday's flux-accounting meeting and today's coffee hour. There was a consensus creating a fairtree library will position flux-accounting for our future work. 

- INPUT: An account-tree object loaded from the flux-accounting database (So a separate load code needs to be developed and @cmoussa1 agreed to take a crack at this)

- PROCESSING: perform "sorting depth first visit" on this tree to compute fairshare values for each and every account in the account tree

- OUTPUT: Updated account-tree object (So a separate flush code needs to be developed to update the new states into the flux-accounting database and @cmoussa1 agreed to take a crack at this)

The library approach will allow flux-accounting to remain agile until our next architectural decision is made.

**Comment by dongahn** [comment]
@garlick mentioned this as a reference: https://github.com/flux-framework/flux-sched/pull/275

**Comment by dongahn** [comment]
Flux architecture has significantly changed since this writeup. But FWIW: https://github.com/flux-framework/flux-sched/wiki/Job-Priority-Plugin-Implementation-Notes

**Comment by garlick** [comment]
Actually I think this one:
https://github.com/flux-framework/flux-sched/wiki/Note-About-The-Flux-Fair-Share-Algorithm

**Comment by garlick** [comment]
On branding, If I put "fairness" into google translate, I find lots of great sounding words!

Norwegian: rettferdighet
Swedish: rättvisa
Latin: aeque
Korean: gongpyeong
Estonian: õiglus

Anyway.

**Comment by dongahn** [comment]
@garlick: 

> Actually I think this one:
https://github.com/flux-framework/flux-sched/wiki/Note-About-The-Flux-Fair-Share-Algorithm

Ah... this is indeed useful.

If I read this correctly, the main challenge with fair tree is difficulty in understanding how it calculates fair share.

I suspect this problem is two-fold: 1) poor documentation to explain the fair tree algorithm and 2) lack of user-level tools to assist users with reasoning about their current fare shares. 

Like you suggested we can significantly improve 1) by more clearly describing this algorithm in simple terms in an RFC; 2) can be improved by adding some tool support. 

To me this algorithm was described as overly "complicated," which shouldn't be the case. 

At its core, you have an account hierarchy (or tree). You do a depth first walk on the tree by descending to a tree node with highest shares-per-usage first. The relative fair share is equal to this visit order. So... if the front tool (e.g., `flux account print-hierarchy`) has an option to print the account in this visit order, users may get a better understanding on their relative faire shares with respect to other users.

**Comment by dongahn** [comment]
The background "hierarchical scheduling" sections of this paper describes the general concept pretty well: https://people.eecs.berkeley.edu/~alig/papers/h-drf.pdf.

**Comment by cmoussa1** [comment]
Okay, so my C++ implementation for `print-hierarchy` currently performs a traversal of the flux-accounting database and can print its values to create an output similar to `sshare`.

```
Bank|User|RawShares|RawUsage
A||1
 B||1
  D||1
   D|user1|1
  E||1
 C||1
  F||1
   F|user2|1
   F|user3|1
  G||1
   G|user4|1
```

I believe the plan for loading the account-tree object into @dongahn's fair tree library would be to similarly traverse the database, starting at the root bank and working down to each leaf bank. Instead of adding each row to a string, however, we would add them to the account-tree object (which I think would be similar to the 
 code in `src/fairness/weighted_tree/test/weighted_load.cpp`):

```c++
node = std::make_shared<weighted_tree_node_t> (
        ancestors.empty ()? nullptr : ancestors.back ().get (),
        is_user? result[2] : result[1],
        is_user,
        std::stoll (result[3]), std::stoll (result[4]));
```

Now that we have usage factors for user rows in the `association_table`, we should be able create a node for every user and bank. Where I think I might need help is propagating the usage values _up_ from users' usage values to their bank and up to a parent bank and so on and so forth up to the root bank. 

But I will try this today and see how far I can get.

**Comment by garlick** [comment]
> I believe the plan for loading the account-tree object into @dongahn's fair tree library

Is "weighted tree" the correct terminology as of #65?  Reminder: fairtree refers to a specific slurm algorithm.  This issue should probably be renamed.

**Comment by cmoussa1** [comment]
> This issue should probably be renamed.

You're right, my mistake. Will make those corrections now.

**Comment by dongahn** [comment]
Yes this sounds good. If you need any help, let me know. I'll be busy this morning but the afternoon should be fairly okay.

**Comment by cmoussa1** [comment]
Thanks @dongahn. I think I am making okay progress so far, I just have a general question about how compiling while also linking to your C++ files:

Essentially I have this directory structure:

```console
[fairness]$ tree
.
|-- Makefile
|-- Makefile.am
|-- Makefile.in
|-- account
|   |-- account.cpp
|   `-- account.hpp
|-- print_hierarchy
|   |-- Makefile
|   |-- Makefile.am
|   |-- Makefile.in
|   `-- print_hierarchy.cpp
`-- weighted_tree
    |-- Makefile
    |-- Makefile.am
    |-- Makefile.in
    |-- test
    |   |-- Makefile
    |   |-- Makefile.am
    |   |-- Makefile.in
    |   |-- accounting_database_load.cpp <-- i added this file here
    |   |-- accounts_data
    |   |   |-- minimal.csv
    |   |   |-- small_no_tie.csv
    |   |   |-- small_tie.csv
    |   |   |-- small_tie_all.csv
    |   |   |-- small_tie_diff_type.csv
    |   |   `-- small_zero_shares.csv
    |   |-- weighted_tree_load.cpp
    |   |-- weighted_tree_load.hpp
    |   `-- weighted_tree_test01.cpp
    |-- weighted_tree.cpp
    |-- weighted_tree.hpp
    |-- weighted_walk.cpp
    `-- weighted_walk.hpp
```

where i added **accounting_database_load.cpp** to `fairness/weighted_tree/test/` . I want to include some of the things yu created, like the `weighted_tree_node_t::weighted_tree_node_t` type you defined in `fairness/weighted_tree/weighted_tree.cpp`. I believe I need to write an #include statement at the top of my file that points here:

```c++
#include "src/fairness/weighted_tree/weighted_tree.hpp"
```

But I am unsure how to compile **accounting_database_load.cpp** into a binary executable that I can run on the command line, just for my own testing purposes. How can I compile while linking your libraries?

**Comment by cmoussa1** [comment]
An update on my progress:

I was able to re-use a lot of the code I had written in **print_hierarchy.cpp** to hierarchically traverse the flux-accounting database, starting at a root bank and going down to each leaf bank and its set of users. Except this time, instead of appending each row to a multi-line hierarchy string, I added them to a vector of tuples which then get written to a `.csv` file in the same format as the test files. So the following database hierarchy:

```
A
 B
  user1
  user2
  user3
 C
  user4
  user5
 D
  E
   F
    user6
```

gets converted into the following `.csv` (I just made up usage values for some of the users):

```
0,A,%^+_nouser,1,0
1,B,%^+_nouser,1,0
2,B,user1,1,1000 <-- fake usage values
2,B,user2,1,1050
2,B,user3,1,0
1,C,%^+_nouser,1,0
2,C,user4,1,0
2,C,user5,1,2500
1,D,%^+_nouser,1,0
2,E,%^+_nouser,1,0
3,F,%^+_nouser,1,0
4,F,user6,1,500
```

And with this format, I'm able to call the `load_weighted_tree` function and pass in the hierarchy:

```c++
std::shared_ptr<weighted_tree_node_t> root = nullptr;
int rc = 0;

rc = load_weighted_tree ("loaded_accounting_db.csv", root);
```

And walk the hierarchy and print out the users in their fairshare order:

```c++
weighted_walk_t walker (root);

walker.run ();
const auto &users = walker.get_users ();

for (unsigned int i=0; i < users.size(); i++) {
  std::cout << users[i]->get_name() << std::endl;
}
```

```console
user3
user4
user6
user1
user2
user5
```

**Comment by dongahn** [comment]
@cmoussa1 and I talked about this a bit. The direction so far looks good to build up the testing environment for flux-accounting + weighted tree library.

This will lead us to easily develop the client side of our weighted-tree fairshare plugin.

We should have more discussion on the server side of our weighted-tree fairshare plugin. And at today's team meeting, @grondo asked us to provide our feedback to the PR: https://github.com/flux-framework/flux-core/pull/3464

**Comment by cmoussa1** [comment]
Small nit I noticed while testing my load accounting database code:

One of the sample `.csv` files **small_tie_diff_type.csv** has the following hierarchy structure:

```
root
 leaf.0.1 <-- leaf node
 account1 <-- sub bank
  leaf.1.1
  leaf.1.2
 account3 <-- sub bank
  leaf.3.1
  leaf.3.2
```

However, I don't think we will have a case where a leaf node exists on the same level as a sub bank.

**Comment by dongahn** [comment]
> However, I don't think we will have a case where a leaf node exists on the same level as a sub bank.

Hmmm, this isn't true at least for our current LC bank hierarchy. I took `sshare` output from Corona and gave it to you. As an example, `amd` is a leaf node which is a sibling of `asc` which is a bank.

**Comment by cmoussa1** [comment]
Just grabbed it from you, thanks. I probably should have been clearer, sorry about that. I think what I am trying to say is `amd` might be a leaf node, but it is not a user. It is just a sub bank with no users in it. In the **small_tie_diff_type.csv** case, `leaf.0.1` is a user, but it exists on the same level as sub banks.

**Comment by ryanday36** [comment]
I don't think we would see the exact situation as that example, but not quite for the reason that Chris stated. I believe that the children of a given node will always be either users or banks (nodes), but not both. So, on corona, amd and asc are both children of root. The children of amd are all users and the children of asc are all banks.

**Comment by dongahn** [comment]
> Just grabbed it from you, thanks. I probably should have been clearer, sorry about that. I think what I am trying to say is from the output you gave me, amd might be a leaf node, but it is not a user. It is just a sub bank with no users in it. In the small_tie_diff_type.csv case, leaf.0.1 is a user, but it exists on the same level as sub banks.

Ah. Thank you for the clarification @cmoussa1 and @ryanday36. 

It seems this is limitation of a specific implementation (SLURM). Is there any reason to continue to "enforce" this constraint if our implementation doesn't have to have it? 

What will be our disadvantage  if Flux can support it so that the children of a given node can have both users AND banks?

**Comment by dongahn** [comment]
> So, on corona, amd and asc are both children of root. The children of amd are all users and the children of asc are all banks.

@ryanday36: BTW, one interesting thing about `amd` is that it currently has no users but has RawUsage. I guess that's because it used to have some users under neath it...

```
             Account       User  RawShares  NormShares    RawUsage  EffectvUsage  FairShare
-------------------- ---------- ---------- ----------- ----------- ------------- ----------
root                                          0.000000  1202435147      1.000000
 amd                                 17920    0.017920       18745      0.000016
 asc                                241026    0.241026     7405134      0.006160
  asccasc                            10000    0.041489     7377941      0.996328
```

**Comment by ryanday36** [comment]
> It seems this is limitation of a specific implementation (SLURM). Is there any reason to continue to "enforce" this constraint if our implementation doesn't have to have it?
> 
> What will be our disadvantage if Flux can support it so that the children of a given node can have both users AND banks?

I don't see any disadvantage to allowing a node to have users and banks under it as long as it doesn't cause any extra headaches for you guys on the back end. It's entirely possible that it's a holdover from an older fair share algorithm or something.

Also, yes, my assumption would be that there used to be users under amd on corona, but they don't have accounts on the cluster anymore.

**Comment by dongahn** [comment]
No there was no extra overheads and complexity in libweighted_tree.

**Comment by cmoussa1** [comment]
Just wanted to update this issue based on the outline of objectives at the top of this thread:

> INPUT: An account-tree object loaded from the flux-accounting database (So a separate load code needs to be developed and @cmoussa1 agreed to take a crack at this)

This objective should now be handled by #97 and #103. The `fairness` directory now contains a subdirectory called `reader`, which will store reader classes that take flux-accounting information and load it into a weighted tree object. For now, there is one sub class called `data_reader_db` which will load information from a SQLite database to a weighted tree object. 

> PROCESSING: perform "sorting depth first visit" on this tree to compute fairshare values for each and every account in the account tree

This objective was handled by #65.

> OUTPUT: Updated account-tree object (So a separate flush code needs to be developed to update the new states into the flux-accounting database and @cmoussa1 agreed to take a crack at this)

This objective is handled partly by #109: an updated account-tree object can now be output with a new subcommand: `flux shares`. One of the last steps will consist of a couple of sub-steps that come to mind right away:

- Updating new fairshare values into the flux-accounting database when new values are calculated
- Adding this fairshare value to the output of `flux shares`

**Comment by dongahn** [comment]
Sounds great. Thank you.
