### ISSUE TITLE
autoconf generates config.py

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-accounting#76]
We discussed this from today's coffee hour. `config.py` can have some variables pertaining to the Flux installation and flux-accounting proper can use them to determine default locations of things. (We also discussed that we will ultimately need TOML support to allow admins to override where the flux-accounting database etc can be found).

**Comment by SteVwonder** [comment]
This was solved as part of #73. Closing. (Sorry for missing the issue references in the commit message).
