### ISSUE TITLE
priority plugin: factor gap analysis

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#8]
As discussed in our remote coffee hour yesterday, and a little in #7, I think this might be a good place to record our gap analysis for multi-factor job priority. I'll make a table listing the factors used, and we can edit this comment as we look at what we currently have in our architecture vs. what we don't. 

| Factor | Description | does Flux already manage this?  |
| ------ |  ----------- | -------------------------------- |
| Age     | the length of time a job has been waiting in the queue, eligible to be scheduled | job-manager's `t_submit` |
| Association | a factor associated with each association |  this could be managed in its own table in **flux-framework/flux-accounting/create_db.py**, which is planned to contain an association table for each cluster |
| Fair-share | the difference between the portion of the computing resource that has been promised and the amount of resources that has been consumed | we discussed multiple approaches on how this would be implemented, but one idea would be to have a `fairshare.py` program that can calculate a fairshare value for a user when its userid is passed in |
| Job size | the number of nodes or CPUs a job is allocated |      |
| Nice | a factor that can be controlled by users to prioritize their own jobs | job-manager's `priority` |
| Partition | a factor associated with each node partition |       |
| QOS | a factor associated with each Quality Of Service |      |
| Site | a factor dictated by an administrator or a site-developed job_submit or site_factor plugin |     |
| TRES | each TRES Type has its own factor for a job which represents the number of requested/allocated TRES Type in a given partition |       |

Each of these factors can be assigned their own weight from 0 to 1. For example, we could place a greater weight on fair-share (or fair-tree) and reduce the weight on Site or QOS. These factors produce a weighted sum using all of the factors listed:

```
Job_priority =
	site_factor +
	(PriorityWeightAge) * (age_factor) +
	(PriorityWeightAssoc) * (assoc_factor) +
	(PriorityWeightFairshare) * (fair-share_factor) +
	(PriorityWeightJobSize) * (job_size_factor) +
	(PriorityWeightPartition) * (partition_factor) +
	(PriorityWeightQOS) * (QOS_factor) +
	SUM(TRES_weight_cpu * TRES_factor_cpu,
	    TRES_weight_<type> * TRES_factor_<type>,
	    ...)
	- nice_factor
```

example configuration:

```
PriorityType=priority/multifactor
PriorityWeightAge=1000
PriorityWeightFairshare=99000
PriorityWeightJobSize=0
PriorityWeightQOS=200000
```

This would result in an equation like the following. If no specific weight is listed in the .conf file, I believe its default value is 1.  
 
```
Job_priority =
	site_factor +
	(1000) * (age_factor) +
	(1) * (assoc_factor) +
	(99000) * (fair-share_factor) +
	(0) * (job_size_factor) +
	(1) * (partition_factor) +
	(200000) * (QOS_factor) +
	SUM(TRES_weight_cpu * TRES_factor_cpu,
	    TRES_weight_<type> * TRES_factor_<type>,
	    ...)
	- nice_factor
```

**Comment by grondo** [comment]
We should ensure our implementation makes it easy to add new factors. On the surface at least, that seems trivial.

Then, determine which of the above factors are *necessary* for use at our site, and start with those.

Finally, I think *Age* and *Nice* may already be handled by the job-manager's `t_submit` and primary `priority`. As we've assumed all along, *Fair-share* is probably the next most important priority factor.

Maybe someone in LC could sort the other factors in order of importance.

**Comment by cmoussa1** [comment]
Just to append to the note on the TRES priority factor:

From the Slurm docs it looks like we can set priorities for specific resources requested by a user. For example:

```
PriorityWeightTRES=CPU=1000,Mem=2000,GRES/gpu=3000
```

which sets a higher priority for GPUs compared to memory and CPUs. Their list of TRES is as follows:

- BB (burst buffers)
- Billing
- CPU
- Energy
- FS (filesystem)
- GRES
- IC (interconnect)
- License
- Mem (Memory)
- Node
- Pages
- VMem (Virtual Memory/Size)

**Comment by cmoussa1** [comment]
Now that #122 has landed and I have had some offline follow-up discussions on the direction the priority plugin is headed, I figured it might be worthwhile to update this table with the factors now implemented along with which factors are currently planned to be implemented. The priority of each factor to be implemented in is indicated by their position on the table.

| Factor | Description | implemented? |
| ------ |  ----------- | -------------------------------- |
| fair share | the difference between the portion of the computing resource that has been promised and the amount of resources that has been consumed | ✓ |
| urgency | a factor that can be controlled by users to prioritize their own jobs | ✓ |
| QOS | a factor associated with each Quality Of Service |      |
| queue | a factor associated with each queue |       |
| age | the length of time a job has been waiting in the queue, eligible to be scheduled |  |
| job size | the number of nodes or CPUs a job is allocated |      |

I think I'll plan on opening a follow-up issue(s) for each of the not-yet-implemented factors to discuss in more detail how these will fit in to our priority plugin.

**Comment by cmoussa1** [comment]
We have a couple of more specific issues open at this point talking about the limits and various factors to be supported in the priority plugin, so I think I'll close this for now.
