### ISSUE TITLE
[discussion] where should multi-factor priorities be enforced

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-accounting#9]
Spin off from https://github.com/flux-framework/flux-accounting/issues/7#issuecomment-601341107

> We still haven't decided whether multi-factor priority plugin will sort jobs at the job-manager level or the external scheduler (e.g., flux-sched) level. While my preference is to do this at the job-manager level, we have to ensure this will not lead to "ALLOC" thrashing problem. Let me open up a ticket and reason about whether the "ALLOC" thrashing will be a real issue or not.

This really goes back to how often multi-factor priorities could lead to a job ordering change in `job-manager`. Maybe we can reason about this step by step by looking at one factor at a time and also whether there will be combined effect when multiple factors interplay (e.g., queue time + job size...)

**Comment by cmoussa1** [comment]
I'll go ahead and paste the multi-factor priorities here to save everybody some clicks 😃:

| Factor | Description | 
| ------ |  ----------- | 
| Age     | the length of time a job has been waiting in the queue, eligible to be scheduled | 
| Association | a factor associated with each association | 
| Fair-share | the difference between the portion of the computing resource that has been promised and the amount of resources that has been consumed | 
| Job size | the number of nodes or CPUs a job is allocated |     
| Nice | a factor that can be controlled by users to prioritize their own jobs | 
| Partition | a factor associated with each node partition |      
| QOS | a factor associated with each Quality Of Service |     
| Site | a factor dictated by an administrator or a site-developed job_submit or site_factor plugin |    
| TRES | each TRES Type has its own factor for a job which represents the number of requested/allocated TRES Type in a given partition |

**Comment by cmoussa1** [comment]
Moving the discussion from https://github.com/flux-framework/flux-sched/issues/638#issuecomment-629563041 to this issue:

> 1. How will our priority calculation plugin get the "queue" information when it is inherently `qmanager` info?

Well, I _think_ in Slurm's case, specific queue information is defined in a configuration file. From Slurm's [documentation](https://slurm.schedmd.com/slurm.conf.html):

> The partition configuration permits you to establish different job limits or access controls for various groups (or partitions) of nodes. Nodes may be in more than one partition, making partitions serve as general purpose queues. For example one may put the same set of nodes into two different partitions, each with different constraints (time limit, job sizes, groups allowed to use the partition, etc.).

**Comment by cmoussa1** [comment]
Just to re-iterate what @dongahn [mentioned](https://github.com/flux-framework/flux-sched/issues/638#issuecomment-629565666) in the other issue thread in flux-sched, another point could be made that there is a distinction between multi-factor _priorities_ and user policy _limits_. I'll mention it here too, but the accounting side could most likely be the place to store those policy _limits_ (**shares**, **max jobs**, and **max wall time per job** are defined for each association as of now). 

Multi-factor priorities include factors that are mentioned in the table above, both static and dynamic. In Slurm, these factors are defined across _all_ of the queues via a configuration file. An example configuration:

```
PriorityType=priority/multifactor
PriorityWeightAge=1000
PriorityWeightJobSize=2000
PriorityWeightFairshare=10000
```

where the higher the number, the more important that factor. Then, specific queue _limits_ are defined further down in the configuration file: An example:

```
QueueName=pdebug Nodes=<node range> DefaultTime=<time> MaxNodes=<max nodes> MaxTime=<time> 
```

I am not 100% sure, but I believe these queue limits would take precedence over the limits defined for each association (which are defined in flux-accounting).

**Comment by cmoussa1** [comment]
I think we have a pretty good idea of where we want to enforce these multi-factor priorities (in our plugin in flux-accounting since #122 was merged), so I think I can close this issue.
